import React, { useMemo } from 'react';
import { ITINERARY_TEMPLATES, VIBES } from '../data/vibedata';
import { useApp } from '../context/AppContext';
import { Clock, MapPin, CheckSquare, Sparkles, CalendarDays, Download } from 'lucide-react';

function downloadItinerary(items, venueName, vibe) {
  const lines = [
    '╔════════════════════════════════╗',
    '║       🌹  VIBEDATE PLAN  🌹       ║',
    '╚════════════════════════════════╝',
    '',
    `Venue: ${venueName || 'To be decided'}`,
    `Vibe: ${vibe ? vibe.charAt(0).toUpperCase() + vibe.slice(1) : 'All vibes'}`,
    '',
    '── TIMELINE ──────────────────────',
    '',
    ...items.map(item => `${item.time}  ${item.icon}  ${item.activity}\n          ${item.detail}`),
    '',
    '── Generated by VibeDate ─────────',
    '   vibedate.app | Bhopal 💕',
  ];
  const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = 'vibedate-itinerary.txt';
  a.click();
}

export default function ItineraryBuilder() {
  const { selectedVenue, selectedVibe, cartItems, selectedGifts, total, budget } = useApp();

  const vibe = selectedVibe || selectedVenue?.vibe || 'romantic';
  const template = ITINERARY_TEMPLATES[vibe] || ITINERARY_TEMPLATES.romantic;

  const itinerary = useMemo(() => {
    return template.map(item => ({
      ...item,
      activity: item.activity.replace(/\{venue\}/g, selectedVenue?.name || 'your chosen venue'),
      detail: item.detail.replace(/\{venue\}/g, selectedVenue?.name || 'your chosen venue'),
    }));
  }, [template, selectedVenue]);

  const vibeInfo = VIBES.find(v => v.id === vibe);

  return (
    <section id="itinerary" className="py-20 px-4 sm:px-6 lg:px-8 max-w-5xl mx-auto">
      <div className="text-center mb-10 space-y-3">
        <div className="inline-flex items-center gap-2 px-4 py-1.5 bg-amber-50 border border-amber-200 rounded-full">
          <span className="text-xs font-black text-amber-700 uppercase tracking-widest">Bonus Feature</span>
        </div>
        <h2 className="text-3xl sm:text-4xl font-black tracking-tight text-gray-900">Itinerary Builder</h2>
        <p className="text-gray-500 text-sm max-w-xl mx-auto">
          A chronological timeline of your perfect date — auto-generated based on your vibe and venue selection.
        </p>
      </div>

      <div className="grid lg:grid-cols-3 gap-6">
        {/* Timeline */}
        <div className="lg:col-span-2">
          <div className="bg-white rounded-3xl border border-pink-100 shadow-xl p-6">
            <div className="flex items-center justify-between mb-6">
              <div className="flex items-center gap-2">
                <CalendarDays className="w-5 h-5 text-crimson" />
                <h3 className="text-sm font-black text-gray-800">
                  {vibeInfo?.emoji} {vibeInfo?.label || 'Romantic'} Date Itinerary
                </h3>
              </div>
              <button
                onClick={() => downloadItinerary(itinerary, selectedVenue?.name, vibe)}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-bold bg-lime-50 border border-lime-200 text-lime-700 hover:bg-lime-100 transition-colors"
              >
                <Download className="w-3.5 h-3.5" />
                Save Plan
              </button>
            </div>

            <div className="relative">
              {/* Vertical line */}
              <div className="absolute left-[22px] top-0 bottom-0 w-0.5 bg-gradient-to-b from-crimson/30 via-pink-200 to-transparent" />

              <div className="space-y-0">
                {itinerary.map((item, idx) => (
                  <div key={idx} className="flex gap-4 pb-6 last:pb-0 group">
                    {/* Dot */}
                    <div className="relative shrink-0">
                      <div className="w-11 h-11 rounded-2xl bg-gradient-to-br from-pink-50 to-rose-50 border-2 border-pink-100 flex items-center justify-center text-xl group-hover:border-crimson/40 transition-colors shadow-sm">
                        {item.icon}
                      </div>
                    </div>

                    {/* Content */}
                    <div className="flex-1 pt-1 pb-6 border-b border-gray-50 last:border-0 group-last:pb-0">
                      <div className="flex items-start justify-between gap-2">
                        <div>
                          <div className="flex items-center gap-2">
                            <span className="text-[10px] font-black text-crimson bg-crimson/5 px-2 py-0.5 rounded-full border border-crimson/10 flex items-center gap-1">
                              <Clock className="w-2.5 h-2.5" />
                              {item.time}
                            </span>
                          </div>
                          <div className="text-sm font-black text-gray-900 mt-1">{item.activity}</div>
                          <div className="text-xs text-gray-500 mt-0.5 leading-relaxed italic">{item.detail}</div>
                        </div>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>

        {/* Side: Summary card */}
        <div className="space-y-4">
          {/* Venue card */}
          <div className={`rounded-2xl p-5 border ${selectedVenue ? 'bg-lime-50 border-lime-200' : 'bg-gray-50 border-gray-100'}`}>
            <div className="text-xs font-black text-gray-500 uppercase tracking-widest mb-3">Selected Venue</div>
            {selectedVenue ? (
              <>
                <div className="text-2xl mb-2">{selectedVenue.image}</div>
                <div className="text-sm font-black text-gray-900">{selectedVenue.name}</div>
                <div className="flex items-center gap-1 text-xs text-gray-500 mt-1">
                  <MapPin className="w-3 h-3" />
                  {selectedVenue.location}
                </div>
                <div className="mt-2 text-xs text-lime-700 font-semibold flex items-center gap-1">
                  <Sparkles className="w-3 h-3" />
                  {selectedVenue.vibe} vibe
                </div>
              </>
            ) : (
              <p className="text-xs text-gray-400">No venue selected yet. Choose one in Step 1!</p>
            )}
          </div>

          {/* Plan summary */}
          <div className="bg-white rounded-2xl border border-pink-100 shadow-sm p-5 space-y-3">
            <div className="text-xs font-black text-gray-500 uppercase tracking-widest">Plan Summary</div>
            <div className="space-y-2">
              <div className="flex justify-between text-xs">
                <span className="text-gray-600">Menu items</span>
                <span className="font-bold text-gray-800">{cartItems.length} items</span>
              </div>
              <div className="flex justify-between text-xs">
                <span className="text-gray-600">Gifts</span>
                <span className="font-bold text-gray-800">{selectedGifts.length} items</span>
              </div>
              <div className="flex justify-between text-xs border-t border-gray-100 pt-2">
                <span className="text-gray-600">Total spend</span>
                <span className={`font-black ${total > budget ? 'text-red-600' : 'text-lime-600'}`}>
                  ₹{total.toLocaleString('en-IN')}
                </span>
              </div>
              <div className="flex justify-between text-xs">
                <span className="text-gray-600">Budget</span>
                <span className="font-bold text-gray-800">₹{budget.toLocaleString('en-IN')}</span>
              </div>
            </div>
          </div>

          {/* Checklist */}
          <div className="bg-white rounded-2xl border border-pink-100 shadow-sm p-5 space-y-3">
            <div className="text-xs font-black text-gray-500 uppercase tracking-widest flex items-center gap-1.5">
              <CheckSquare className="w-3.5 h-3.5" />
              Pre-Date Checklist
            </div>
            {[
              { label: 'Venue booked/reserved', done: !!selectedVenue },
              { label: 'Menu items planned', done: cartItems.length > 0 },
              { label: 'Gift selected', done: selectedGifts.length > 0 },
              { label: 'Message written', done: false },
              { label: 'Outfit decided', done: false },
              { label: 'Budget in check', done: total > 0 && total <= budget },
            ].map((item, i) => (
              <div key={i} className="flex items-center gap-2.5">
                <div className={`w-4 h-4 rounded-full border-2 flex items-center justify-center shrink-0 ${
                  item.done ? 'bg-lime-500 border-lime-500' : 'border-gray-200'
                }`}>
                  {item.done && <CheckSquare className="w-2.5 h-2.5 text-white" />}
                </div>
                <span className={`text-xs ${item.done ? 'text-lime-700 font-semibold' : 'text-gray-500'}`}>{item.label}</span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}
